name: Deploy to Brainpod

on:
  push:
    branches: ["main", "feat/brainpod-integration"]
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Build and push
        uses: brainhivenl/steiger-action@v1
        with:
          cmd: build
          args: --repo=registry.brainpod.io/grapes-cross
